title: fleetime ðŸ° # name of the site
author: fleetime # name of site's author
email: novian.andika@students.amikom.ac.id # email of site's author
url: https://fleetime.my.id # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)

permalink: /:slug/

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

toc:
  min_level: 2
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
